# Generated by Django 4.2.26 on 2025-12-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_automation', '0002_repprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='gps_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
